language: erlang
script:
   - rm -rf deps
   - "CONFIG=rebar.tests.config make test && CONFIG=rebar.tests.config make build_plt && CONFIG=rebar.tests.config make dialyzer"
otp_release:
   - R16B01

addons:
  hosts:
    - mailhost.test
